// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NfcHomeManager.Data;

#nullable disable

namespace NfcHomeManager.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261006035404_ProvedeneOperace")]
    partial class ProvedeneOperace
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.12");

            modelBuilder.Entity("NfcHomeManager.Models.Kategorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kategorie");
                });

            modelBuilder.Entity("NfcHomeManager.Models.Lek", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Davkovani")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ean")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Expirace")
                        .HasColumnType("TEXT");

                    b.Property<string>("Interakce")
                        .HasColumnType("TEXT");

                    b.Property<bool>("JeLek")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Jednotka")
                        .HasColumnType("TEXT");

                    b.Property<int>("LekarnickaId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Mnozstvi")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("NaCoJe")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NaPredpis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NezadouciUcinky")
                        .HasColumnType("TEXT");

                    b.Property<string>("Poznamka")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProKoho")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VytvorenoUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LekarnickaId");

                    b.ToTable("Leky");
                });

            modelBuilder.Entity("NfcHomeManager.Models.LekovyKatalog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AtcWho")
                        .HasColumnType("TEXT");

                    b.Property<string>("Baleni")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ean")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Forma")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KodSukl")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("NactenoUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sila")
                        .HasColumnType("TEXT");

                    b.Property<string>("Vydej")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Ean");

                    b.ToTable("LekovyKatalog");
                });

            modelBuilder.Entity("NfcHomeManager.Models.Mistnost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Mistnosti");
                });

            modelBuilder.Entity("NfcHomeManager.Models.Pojisteni", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CisloSmlouvy")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PlatnostDo")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("PlatnostOd")
                        .HasColumnType("TEXT");

                    b.Property<string>("Pojistovna")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PolozkaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Poznamka")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("RocniCenaKc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Typ")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VytvorenoUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PolozkaId");

                    b.ToTable("Pojisteni");
                });

            modelBuilder.Entity("NfcHomeManager.Models.Polozka", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Aktivni")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CenaKc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("DatumPorizeni")
                        .HasColumnType("TEXT");

                    b.Property<string>("Ean")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("Expirace")
                        .HasColumnType("TEXT");

                    b.Property<string>("Jednotka")
                        .HasColumnType("TEXT");

                    b.Property<int?>("KategorieId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Kod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("KontejnerId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("MaVlastniNfcKartu")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("MistnostId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("Mnozstvi")
                        .HasColumnType("decimal(18,3)");

                    b.Property<string>("Model")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nazev")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("NfcUid")
                        .HasColumnType("TEXT");

                    b.Property<string>("Poznamka")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rezim")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SerioveCislo")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SledovatExpiraci")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SledovatPojisteni")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SledovatRevizi")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SledovatServis")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Specializace")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Spz")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpravenoUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Verejna")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Vyrobce")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VytvorenoUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ZarukaDo")
                        .HasColumnType("TEXT");

                    b.Property<int>("ZarukaMesice")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("KategorieId");

                    b.HasIndex("Kod")
                        .IsUnique();

                    b.HasIndex("KontejnerId");

                    b.HasIndex("MistnostId");

                    b.HasIndex("NfcUid")
                        .IsUnique()
                        .HasFilter("NfcUid IS NOT NULL");

                    b.ToTable("Polozky");
                });

            modelBuilder.Entity("NfcHomeManager.Models.ProvedenaOperace", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Presmerovani")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VytvorenoUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("VytvorenoUtc");

                    b.ToTable("ProvedeneOperace");
                });

            modelBuilder.Entity("NfcHomeManager.Models.ServisniZaznam", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("CenaKc")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateOnly?>("DalsiTerminDo")
                        .HasColumnType("TEXT");

                    b.Property<string>("DalsiTerminTyp")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("Datum")
                        .HasColumnType("TEXT");

                    b.Property<int>("PolozkaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Popis")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provozovna")
                        .HasColumnType("TEXT");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VytvorenoUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PolozkaId");

                    b.ToTable("ServisniZaznamy");
                });

            modelBuilder.Entity("NfcHomeManager.Models.Termin", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("DatumDo")
                        .HasColumnType("TEXT");

                    b.Property<int>("PolozkaId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Poznamka")
                        .HasColumnType("TEXT");

                    b.Property<string>("Typ")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpravenoUtc")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("VytvorenoUtc")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("PolozkaId", "Typ")
                        .IsUnique();

                    b.ToTable("Terminy");
                });

            modelBuilder.Entity("NfcHomeManager.Models.Lek", b =>
                {
                    b.HasOne("NfcHomeManager.Models.Polozka", "Lekarnicka")
                        .WithMany("Leky")
                        .HasForeignKey("LekarnickaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Lekarnicka");
                });

            modelBuilder.Entity("NfcHomeManager.Models.Pojisteni", b =>
                {
                    b.HasOne("NfcHomeManager.Models.Polozka", "Polozka")
                        .WithMany("Pojisteni")
                        .HasForeignKey("PolozkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Polozka");
                });

            modelBuilder.Entity("NfcHomeManager.Models.Polozka", b =>
                {
                    b.HasOne("NfcHomeManager.Models.Kategorie", "Kategorie")
                        .WithMany("Polozky")
                        .HasForeignKey("KategorieId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NfcHomeManager.Models.Polozka", "Kontejner")
                        .WithMany("Obsah")
                        .HasForeignKey("KontejnerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("NfcHomeManager.Models.Mistnost", "Mistnost")
                        .WithMany("Polozky")
                        .HasForeignKey("MistnostId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Kategorie");

                    b.Navigation("Kontejner");

                    b.Navigation("Mistnost");
                });

            modelBuilder.Entity("NfcHomeManager.Models.ServisniZaznam", b =>
                {
                    b.HasOne("NfcHomeManager.Models.Polozka", "Polozka")
                        .WithMany("ServisniZaznamy")
                        .HasForeignKey("PolozkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Polozka");
                });

            modelBuilder.Entity("NfcHomeManager.Models.Termin", b =>
                {
                    b.HasOne("NfcHomeManager.Models.Polozka", "Polozka")
                        .WithMany("Terminy")
                        .HasForeignKey("PolozkaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Polozka");
                });

            modelBuilder.Entity("NfcHomeManager.Models.Kategorie", b =>
                {
                    b.Navigation("Polozky");
                });

            modelBuilder.Entity("NfcHomeManager.Models.Mistnost", b =>
                {
                    b.Navigation("Polozky");
                });

            modelBuilder.Entity("NfcHomeManager.Models.Polozka", b =>
                {
                    b.Navigation("Leky");

                    b.Navigation("Obsah");

                    b.Navigation("Pojisteni");

                    b.Navigation("ServisniZaznamy");

                    b.Navigation("Terminy");
                });
#pragma warning restore 612, 618
        }
    }
}
